import 'package:dalotee/data/model/response/card_model.dart';
import 'package:dalotee/generated/assets/assets.gen.dart';

String description =
    'Dẫn nhập: The Fool luôn luôn là người chỉ ra những thứ mới mẻ; cũng giống như sự thuần khiết và năng lượng cởi mở của một đứa trẻ. Đây nhìn chung được xem là một lá bài tích cực, với lời báo trước rằng việc dành thời gian để chắc chắn bạn đang “nhìn xem mình đi tới đâu” là rất quan trọng. \n\nTổng quan: Lá bài này biểu hiện những khởi đầu mới mang ý nghĩa Tinh thần sâu sắc – ví dụ, bắt đầu trải nghiệm thiền định hoặc khởi đầu một mối quan hệ, trái ngược hoàn toàn với việc mua một đôi giày mới. Sự xuất hiện của The Fool có thể dự báo một khởi đầu tươi mới quan trọng. \n\nCông việc: Những người khác có thể không hiểu hoặc không ủng hộ ý tưởng mới và/hoặc đề xuất mới của bạn, nhưng nếu bạn biết rằng mình đúng thì cứ tiến tới và cố gắng giúp họ hiểu quan điểm của bạn. Điều này đôi khi sẽ biểu thị một vị trí mới – hay thậm chí là lúc bạn phải “biến quách đi một mình” và bắt đầu công cuộc kinh doanh của chính bạn.\n\n Tình yêu: Khi The Fool xuất hiện thì rất có thể bạn chưa sẵn sàng cho một mối quan hệ mang tính ràng buộc, trong khi trên thực tế những người khác lại đang thúc ép bạn làm như vậy. Nhưng đây là một dấu hiệu tích cực cho mối quan hệ tình cảm của bạn; nhiều điều hay ho dường như đang chờ chực. Chỉ là đừng để ham muốn vui vẻ của bạn khiến bạn bỏ qua “những điều thực” (tình yêu chân chính, đích thực, sâu nặng) khi nó đến với bạn nhé. \n\nTài chính: Trong chuyện tài chính, The Fool là một dấu hiệu tích cực. Bạn có thể trông đợi những sự tăng trưởng, và hơn thế nữa, bạn sẽ tìm thấy trong chính bản thân rằng dù có gì xảy ra về tài chính đi nữa thì bạn vẫn sẽ ổn và sẽ là “kẻ chiến thắng sau hết”. Tin tưởng bản thân, làm việc chăm chỉ, và bạn sẽ làm tốt hơn bạn tưởng đấy. \n\nSức khỏe: Có thể bạn sẽ gặp vài tai nạn nhỏ khi The Fool xuất hiện; hãy “ở hiện tại” và đừng làm những thứ ngốc nghếch. Dù vậy, Tổng quan, khi lá bài này xuất hiện thì sức khỏe của bạn có vẻ đang đi lên. Nếu bạn có vấn đề về sức khỏe, bạn rất có thể tìm thấy người và phương tiện bạn cần để nhanh chóng hồi phục hoàn toàn. Những suy nghĩ tích cực rất quan trọng và có thể dễ dàng đến với bạn lúc này. \n\nTinh thần: Khi lá bài này xuất hiện, bạn có vẻ mong muốn thử trải nghiệm nhiều cách tiếp cận khác nhau đến thế giới Tinh thần để xem chúng “hợp” thế nào. Không có gì là sai trái với việc khám phá tìm hiểu này, tuy nhiên đừng để cái gì cuốn mình đi quá xa trong lúc “trải nghiệm sơ qua”. Lá bài này có thể biểu thị một nhu cầu mạnh mẽ đòi có kiến thức sâu hơn về Tinh thần, và bạn bè cùng gia đình bạn có lẽ sẽ không hiểu nó đến từ đâu. Dù sao đi nữa, thì bạn vẫn phải làm những gì tốt nhất cho bạn thôi.';
String meaning =
    'The Fool là kẻ phiêu lưu, là anh hùng trong chuyến hành trình này. Trong các thuật ngữ nguyên mẫu, anh ta là linh hồn mới sẵn sàng hiện thân trên Trái Đất. Anh ta chẳng có gì để mang theo bên người. Thật ra chúng ta không biết được anh ta mang gì bên trong chiếc túi đó. Có thể là những năng lực bẩm sinh cùng với kiến thức của mục đích sống mà linh hồn bên trong anh ta mang đến cuộc đời này. Anh ta bước về thế giới vô định ở phía trước bằng người bạn đồng hành đáng tin cậy. Con chó trung thành này đại diện cho điều gì? Chúng ta cũng không thật sự biết được điều đó ra sao, tuy nhiên có một ý kiến đáng suy ngẫm rằng con chó đó là hiện thân của trực giác mà The Fool sở hữu… nó kết nối trực tiếp đến mạng lưới của vũ trụ vật lý. Nếu The Fool đủ thông minh, anh ta sẽ chú ý đến nó hơn.\n\nNghĩa tiên đoán: một sự khởi đầu mới, cần phải có lòng dũng cảm và niềm tin, cần phải mạnh dạn bước đi cho dù điều đó là ngốc nghếch.\n\nLời khuyên: hãy lắng nghe những bản năng của mình và làm những gì mà bạn muốn cho dù bạn thấy chúng thật đáng sợ. Chẳng có bằng chứng nào cho thấy chúng sẽ thật sự dễ dàng đối với bạn, thế nhưng điều đó sẽ đưa bạn đến nơi cần phải đến và mang lại cho bạn những kinh nghiệm bạn cần phải có.\n\nNếu bài xoay ngược, hãy tự hỏi mình: mình có đang thật sự theo bước trực giác không hay chỉ là đang trở nên ngu ngốc? Mình có đang buông bỏ sự sỡ hãi để sống một cuộc đời mình mong muốn hay không?\n';
CardData card = CardData(
    name: "The Fool",
    front: Assets.images.imgTheFoolCard.path,
    back: Assets.images.imgBackCard.path,
    description: description,
    meaning: meaning,
    category: "Pentacles");
